baseURL       = "https://www.ensemble-it-coaching.de/"
languageCode  = "de-DE"
title         = "Ensemble IT Coaching"
theme         = "roxo-hugo"
summarylength = 25

relativeURLs = true


# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name    = "Startseite"
url     = ""
weight  = 1
[[menu.nav]]
name    = "Über mich"
url     = "about"
weight  = 2
[[menu.nav]]
name    = "Angebot"
url     = "portfolio"
weight  = 3
[[menu.nav]]
name    = "FAQ"
url     = "about/faq"
weight  = 4
[[menu.nav]]
#name    = "Erfolgsgeschichten"
#url     = "success"
#weight  = 5
[[menu.nav]]
name    = "Kontakt"
url     = "contact"
weight  = 5

# Site Params
[params]
logo = "images/logo-header.svg"
dateFormat = "26 FEB 1994"
# Meta data
description = "Ensemble IT Coaching | "
author = "Ensemble by Anna Breyer"
# Google Analitycs
googleAnalitycsID = "Your ID"
# We're using formspree.io for form handling, paste your formspree url below
fabform  = "https://fabform.io/f/USAg2Jl" #todo

# Contact Form
[params.contactForm]
placeholder_first_name        = "Vorname"
placeholder_last_name         = "Nachname"
placeholder_email             = "Email"
placeholder_project_type      = "Projekt Typ"
placeholder_about_the_project = "Darum es geht"
send_message                  = "Nachricht senden"

[[params.contactForm.projectType]]#todo
value = "gd"
title  = "Graphics Design"
[[params.contactForm.projectType]]
value = "wd"
title  = "Web Design"

# Navbar Action Button
[params.navAction]
status  = true
name    = "Mich kontaktieren" #todo
url     = "contact"


# Banner Section
[params.banner]
enable                = true
background_image      = "images/backgrounds/hero-background_blurry.jpg"
heading               = "Hilfe zur Selbsthilfe für Deine Technik-Probleme"
tagline               = "IT und EDV Coaching von Frau ♀︎ für Frauen* ⚧"
primary_button        = "Mein Angebot"
primary_button_url    = "portfolio"
secondary_button      = "Mich kontaktieren" #todo
secondary_button_url  = "contact"

[params.portfolio]
enable    = true
title     = "MEIN ANGEBOT"
subtitle  = "Damit du dich auf dein Kerngeschäft konzentrieren kannst statt Zeit mit Technik Fragen zu verlieren."

[params.call_to_action]
enable              = true
background_image    = "images/backgrounds/rainbow-background.png"
title               = "Lass uns zusammen arbeiten"
primary_button      = "Anfrage absenden"
primary_button_url  = "contact"
secondary_button    = "Noch nicht sicher?"
secondary_button_url = "portfolio"

[params.footer]
# Footer Contact Info
[params.footer.contactInfo]
title   = "Kontakt Information"
address = "Bahnhofstr. 9, <br> 55278 Hahnheim"
phone   = "+49 174 5124442"
email   = "office@ensemble-it-coaching.de"
# Footer Sitemap
[params.footer.sitemap]
title   = "Sitemap"
[[params.footer.sitemap.link]]
name = "Über mich"
url  = "about"
[[params.footer.sitemap.link]]
name = "Angebot"
url  = "portfolio"
[[params.footer.sitemap.link]]
name = "FAQ"
url  = "about/faq"
#[[params.footer.sitemap.link]]
#name = "Erfolgsgeschichten"
#url  = "success" #todo rename URL
[[params.footer.sitemap.link]]
name = "Kontakt"
url  = "contact"
# Footer Social Media
[params.footer.legal]
title   = "Legales"
[[params.footer.legal.link]]
name = "Datenschutz"
url  = "about/dsgvo"
[[params.footer.legal.link]]
name = "Impressum"
url  = "about/impressum"
# Footer Service
[params.footer.service]
title       = "Ich helfe sebstständigen Frauen*:"
description = "bei Computer Fragen<br>von der Ohnmacht<br>in die Selbstermächtiging<br>zu kommen"