baseURL       = "https://www.ensemble-it-coaching.de/"
languageCode  = "de-DE"
title         = "Ensemble IT Coaching"
theme         = "roxo-hugo"
summarylength = 25

relativeURLs = true


# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name    = "Startseite"
url     = ""
weight  = 1
[[menu.nav]]
name    = "Über mich"
url     = "ueber-mich"
weight  = 2
[[menu.nav]]
name    = "Angebot"
url     = "portfolio"
weight  = 3
[[menu.nav]]
name    = "FAQ"
url     = "ueber-mich/faq"
weight  = 4
[[menu.nav]]
name    = "Kontakt"
url     = "kontakt"
weight  = 5

# Site Params
[params]
logo = "images/logo-header.svg"
dateFormat = "26 FEB 1994"
# Meta data
description = "Ensemble IT Coaching | IT und EDV Coaching von Frau ♀︎ für Frauen* ⚧"
author = "Ensemble by Anna Breyer"
# We're using formspree.io for form handling, paste your formspree url below
#formspree  = "https://formspree.io/f/mnqknyrz"
fabform = "https://fabform.io/f/NjpP9iZ"

# Contact Form
[params.contactForm]
placeholder_first_name        = "Vorname"
placeholder_last_name         = "Nachname"
placeholder_email             = "Email"
placeholder_project_type      = "Typ"
placeholder_about_the_project = "Darum es geht"
send_message                  = "Nachricht senden"

[[params.contactForm.projectType]]
value = "single"
title  = "Hilfe zur Selbsthilfe"
[[params.contactForm.projectType]]
value = "group"
title  = "Veranstaltung"

# Navbar Action Button
[params.navAction]
status  = true
name    = "Mich kontaktieren"
url     = "kontakt"


# Banner Section
[params.banner]
enable                = true
background_image      = "images/backgrounds/hero-background_blurry.jpg"
heading               = "Hilfe zur Selbsthilfe für Deine Technik-Probleme"
tagline               = "IT und EDV Coaching von Frau ♀︎ für Frauen* ⚧"
primary_button        = "Mein Angebot"
primary_button_url    = "portfolio"
secondary_button      = "Mich kontaktieren"
secondary_button_url  = "kontakt"

[params.portfolio]
enable    = true
title     = "MEIN ANGEBOT"
subtitle  = "Damit Du Dich auf Dein Kerngeschäft konzentrieren kannst statt Zeit mit Technik Fragen zu verlieren."

[params.call_to_action]
enable               = true
background_image     = "images/backgrounds/rainbow-background.png"
title                = "Lass uns zusammen arbeiten"
primary_button       = "Anfragen"
primary_button_url   = "kontakt"
secondary_button     = "Noch nicht sicher?"
secondary_button_url = "portfolio"

[params.footer]
# Footer Contact Info
[params.footer.contactInfo]
title   = "Kontakt"
address = "Bahnhofstr. 9, <br> 55278 Hahnheim"
phone   = "+49 174 5124442"
email   = "office@ensemble-it-coaching.de"
# Footer Sitemap
[params.footer.sitemap]
title   = "Sitemap"
[[params.footer.sitemap.link]]
name = "Über mich"
url  = "ueber-mich"
[[params.footer.sitemap.link]]
name = "Angebot"
url  = "portfolio"
[[params.footer.sitemap.link]]
name = "FAQ"
url  = "ueber-mich/faq"
[[params.footer.sitemap.link]]
name = "Kontakt"
url  = "kontakt"
# Footer Social Media
[params.footer.legal]
title   = "Legales"
[[params.footer.legal.link]]
name = "Datenschutz"
url  = "ueber-mich/dsgvo"
[[params.footer.legal.link]]
name = "Impressum"
url  = "ueber-mich/impressum"
# Footer Service
[params.footer.service]
title       = "Ich helfe sebstständigen Frauen*:"
description = "bei Computer Fragen<br>von der Ohnmacht<br>in die Selbstermächtiging<br>zu kommen"